corgi = Breed.create(name:'Corgi')
frenchie = Breed.create(name:'French Bulldog')
Mutt = Breed.create(name:'Mutt')
Grehound = Breed.create(name:'Greyhound')

Dog.create([
    {name: 'Tito', breed_id: '1', age: '1', location: 'Riverside, CA', description: 'Super cute pup! AKC certified. Loves cuddles.', image_url: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Ff%2Ffb%2FWelchcorgipembroke.JPG&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPembroke_Welsh_Corgi&tbnid=Ja4xPimgkXmtSM&vet=12ahUKEwiy7oiZyLnrAhUCjJ4KHcx1AV8QMygAegUIARDJAQ..i&docid=BBJ_9I_2GxfuBM&w=2967&h=1978&q=corgi%20images&ved=2ahUKEwiy7oiZyLnrAhUCjJ4KHcx1AV8QMygAegUIARDJAQ'},
    {name: 'Gale', breed_id: '4', age: '10', location: 'Upland, CA', description: 'Overgrown cat. AKA retired greyhound. This dog is here for all the cuddles and is perfect for families.', image_url: 'https://minnesotagreyhoundrescue.org/wp-content/uploads/2017/10/14448841_10208815550160338_806195778504773190_n.jpg'},
    {name: 'Alice', breed_id: '4', age: '5', location: 'Rancho Cucamonga, CA', description: 'Kinda timid, but super friendly. A dog that finds happiness in pleasing its owners!', image_url: 'https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.birminghamracecourse.com%2Fimages%2Fadoptiongreyhound.jpg&imgrefurl=http%3A%2F%2Fwww.birminghamracecourse.com%2Fadoption.html&tbnid=2XzHq691ryEfgM&vet=12ahUKEwjc3pPOybrrAhU6FTQIHcJMBs8QMygGegUIARDOAQ..i&docid=Qzlh1emNPmv0CM&w=572&h=270&q=greyhound%20rescue&ved=2ahUKEwjc3pPOybrrAhU6FTQIHcJMBs8QMygGegUIARDOAQ'},
    {name: 'Yoda', breed_id: '3', age: '10', location: 'Fontana, CA', description: 'Cute dog. Kinda an airhead but that is part of her charm!', image_url: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn2-www.dogtime.com%2Fassets%2Fuploads%2Fgallery%2Fmutt-dog-breed-pictures%2Fface-1.jpg&imgrefurl=https%3A%2F%2Fdogtime.com%2Fdog-breeds%2Fmutt&tbnid=pX1flz_rcnq2eM&vet=12ahUKEwjg75HFyrrrAhWxCjQIHZ_JBq0QMygEegUIARDXAQ..i&docid=QeekHzGmvMVpmM&w=680&h=617&q=mutt%20dog&ved=2ahUKEwjg75HFyrrrAhWxCjQIHZ_JBq0QMygEegUIARDXAQ'},
    {name: 'Flatface', breed_id: '2', age: '2', location: 'Orange, CA', description: 'Genetically mutated dog', image_url: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fd17fnq9dkz9hgj.cloudfront.net%2Fbreed-uploads%2F2018%2F08%2Ffrench-bulldog-card-small.jpg%3Fbust%3D1535568664&imgrefurl=https%3A%2F%2Fwww.petfinder.com%2Fdog-breeds%2Ffrench-bulldog%2F&tbnid=L3t821FTCUcKtM&vet=12ahUKEwiSnaDoyrrrAhUCAzQIHeNRDKIQMygHegUIARDyAQ..i&docid=XOF0IW3QrAfoFM&w=1274&h=520&q=french%20bulldog&ved=2ahUKEwiSnaDoyrrrAhUCAzQIHeNRDKIQMygHegUIARDyAQ'},
    {name: 'Fatty', breed_id: '2', age: '4', location: 'Dallas, TX', description: 'Cute.', image_url: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F7%2F7a%2FSupermillion_Visuals_-_Aston_Fresh_Park_1-02601.jpg&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFrench_Bulldog&tbnid=awZ5OZAAQzLADM&vet=12ahUKEwiSnaDoyrrrAhUCAzQIHeNRDKIQMygAegUIARDhAQ..i&docid=xU-lZz4nwwmcBM&w=2832&h=4240&q=french%20bulldog&ved=2ahUKEwiSnaDoyrrrAhUCAzQIHeNRDKIQMygAegUIARDhAQ'}
])